#!/usr/bin/python

import sys, os, platform

IP = sys.argv[1]

cmd = "snmpwalk -v 2c -c ObviouslyThisIsNotMyCommunityString %s NET-SNMP-EXTEND-MIB::'nsExtendOutputFull.\"ThorSlave\"'|awk -F'STRING: ' '{print $2}'" % IP

check_remote = os.popen(cmd).readline()

try:

        if "ThorSlave not running" in check_remote:
                print "WARNING - ThorSlave process appears not to be running" 
                sys.exit(1)
        elif "ThorSlave is running" in check_remote:
                print "ThorSlave OK" 
                sys.exit(0)

except ValueError:
        print "Unable to connect to server or SNMP down"
        sys.exit(2)

