#!/usr/bin/python

import sys, os, platform

IP = sys.argv[1]

cmd = "snmpwalk -v 2c -c ObviouslyThisIsNotMyCommunityString %s NET-SNMP-EXTEND-MIB::'nsExtendOutputFull.\"ECLCCServer\"'|awk -F'STRING:' '{print $2}'" % IP

check_remote = os.popen(cmd).readline().replace('|','').replace('\n','')

try:

        if "is running" in check_remote:
                print check_remote 
                sys.exit(0)
        elif "is stopped" in check_remote:
                print check_remote 
                sys.exit(2)
	else:
		print "Unknown status"
		sys.exit(1)

except ValueError:
        print "Unable to connect to server or SNMP down"
        sys.exit(2)

